### ISSUE TITLE
Installation fails: launcher: error: --launcher-config option requires an argument

### ISSUE THREAD

**Issue by jakovm** [prestodb/ambari-presto-service#15]
Hi there,
I can't get presto to run. During the installation procedure I always receive following failure message. I run it on Centos 7. Java 1.8.0_45 jdk is installed and everything configured as described in the docu.

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/PRESTO/package/scripts/presto_worker.py", line 73, in <module>
    Worker().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 218, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.3/services/PRESTO/package/scripts/presto_worker.py", line 37, in start
    Execute('{0} start'.format(daemon_control_script))
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 157, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 152, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 118, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 258, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
    tries=tries, try_sleep=try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 291, in _call
    raise Fail(err_msg)
resource_management.core.exceptions.Fail: Execution of '/etc/init.d/presto start' returned 2. Starting presto 
Warning: No value found for JAVA8_HOME. Default Java will be used.
Usage: launcher [options] command

launcher: error: --launcher-config option requires an argument

**Comment by petroav** [comment]
I suspect the problem is that Ambari is not set to run with Java 8. You can set the JDK used by Ambari through the `java.home` property in `/etc/ambari-server/conf/ambari.properties`. However I don't know if this will propagate to the Ambari agents (and Presto workers) so they start using that JDK as well. I'm currently trying to reproduce this locally to make sure the agents start using the right JDK as well.

**Comment by petroav** [comment]
So I just tried installing Presto with Ambari running JDK 7 and the installation failed, albeit at a different point. The installation failed when trying to install the RPM, which is before starting Presto. The reason why the RPM installation fails is because the RPM preinstall scripts checks the system for Java 8 and if it can't find any, it will fail. So I don't know how you got yourself in a state where you managed to install the Presto RPM but then the start script can't find the right Java.

After my little experiment, I edited `java.home` in `/etc/ambari-server/conf/ambari.properties` on the Ambari master to point to the JDK 8 that Ambari downloaded in `/usr/jdk64/jdk1.8.0_60/`. I then re-installed one of the Presto workers, whose installation had previously failed, and it succeeded. That node now also has Java 8 in `/usr/jdk64/jdk1.8.0_60/`, whereas before it didn't. I think Ambari transparently copied the JDK over when it detected that the slave didn't have it.

What do you get when you run `java -version` on the node where Presto failed to start?

**Comment by petroav** [comment]
My bad, Ambari will NOT copy over the JDK. You need to have it installed in the same location on all nodes. So if you set `java.home` to `/usr/jdk64/jdk1.8.0_60/`, that JDK needs to be in that location on all nodes.

**Comment by jakovm** [comment]
I guess the issue was that I was first installing the ambari-server, setting it up, starting it and afterwards installing the ambari-presto-service and then restart the server. Also somehow there woas java version "1.8.0_45" on it. After removing it and starting from scrach everything works perfect. Thanks for your help!
