### ISSUE TITLE
Centos7:resource_management.core.exceptions.ExecutionFailed: Execution of '/etc/init.d/presto start'

### ISSUE THREAD

**Issue by getway** [prestodb/ambari-presto-service#26]
stderr: 
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/PRESTO/package/scripts/presto_coordinator.py", line 86, in <module>
    Coordinator().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/PRESTO/package/scripts/presto_coordinator.py", line 39, in start
    Execute('{0} start'.format(daemon_control_script))
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 155, in __init__
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 273, in action_run
    tries=self.resource.tries, try_sleep=self.resource.try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 70, in inner
    result = function(command, **kwargs)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 92, in checked_call
    tries=tries, try_sleep=try_sleep)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 140, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 293, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/etc/init.d/presto start' returned 1. Starting presto 
sudo: sorry, you must have a tty to run sudo
 stdout:
2017-01-18 12:36:09,987 - The hadoop conf dir /usr/hdp/current/hadoop-client/conf exists, will call conf-select on it for version 2.5.3.0-37
2017-01-18 12:36:09,990 - Checking if need to create versioned conf dir /etc/hadoop/2.5.3.0-37/0
2017-01-18 12:36:09,993 - call[('ambari-python-wrap', u'/usr/bin/conf-select', 'create-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.3.0-37', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False, 'stderr': -1}
2017-01-18 12:36:10,056 - call returned (1, '/etc/hadoop/2.5.3.0-37/0 exist already', '')
2017-01-18 12:36:10,057 - checked_call[('ambari-python-wrap', u'/usr/bin/conf-select', 'set-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.3.0-37', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False}
2017-01-18 12:36:10,125 - checked_call returned (0, '')
2017-01-18 12:36:10,127 - Ensuring that hadoop has the correct symlink structure
2017-01-18 12:36:10,127 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2017-01-18 12:36:10,375 - The hadoop conf dir /usr/hdp/current/hadoop-client/conf exists, will call conf-select on it for version 2.5.3.0-37
2017-01-18 12:36:10,378 - Checking if need to create versioned conf dir /etc/hadoop/2.5.3.0-37/0
2017-01-18 12:36:10,381 - call[('ambari-python-wrap', u'/usr/bin/conf-select', 'create-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.3.0-37', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False, 'stderr': -1}
2017-01-18 12:36:10,443 - call returned (1, '/etc/hadoop/2.5.3.0-37/0 exist already', '')
2017-01-18 12:36:10,444 - checked_call[('ambari-python-wrap', u'/usr/bin/conf-select', 'set-conf-dir', '--package', 'hadoop', '--stack-version', '2.5.3.0-37', '--conf-version', '0')] {'logoutput': False, 'sudo': True, 'quiet': False}
2017-01-18 12:36:10,508 - checked_call returned (0, '')
2017-01-18 12:36:10,509 - Ensuring that hadoop has the correct symlink structure
2017-01-18 12:36:10,510 - Using hadoop conf dir: /usr/hdp/current/hadoop-client/conf
2017-01-18 12:36:10,513 - Group['livy'] {}
2017-01-18 12:36:10,515 - Group['spark'] {}
2017-01-18 12:36:10,516 - Group['ranger'] {}
2017-01-18 12:36:10,516 - Group['hadoop'] {}
2017-01-18 12:36:10,517 - Group['users'] {}
2017-01-18 12:36:10,518 - User['hive'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,519 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,520 - User['infra-solr'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,522 - User['ams'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,523 - User['ranger'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'ranger']}
2017-01-18 12:36:10,524 - User['tez'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users']}
2017-01-18 12:36:10,525 - User['livy'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,527 - User['spark'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,528 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'users']}
2017-01-18 12:36:10,529 - User['kafka'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,530 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,531 - User['yarn'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,533 - User['mapred'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,534 - User['hbase'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,535 - User['hcat'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': [u'hadoop']}
2017-01-18 12:36:10,536 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-01-18 12:36:10,539 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2017-01-18 12:36:10,570 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa'] due to not_if
2017-01-18 12:36:10,571 - Directory['/tmp/hbase-hbase'] {'owner': 'hbase', 'create_parents': True, 'mode': 0775, 'cd_access': 'a'}
2017-01-18 12:36:10,572 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2017-01-18 12:36:10,574 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/tmp/hbase-hbase'] {'not_if': '(test $(id -u hbase) -gt 1000) || (false)'}
2017-01-18 12:36:10,603 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/tmp/hbase-hbase'] due to not_if
2017-01-18 12:36:10,604 - Group['hdfs'] {}
2017-01-18 12:36:10,604 - User['hdfs'] {'fetch_nonlocal_groups': True, 'groups': [u'hadoop', u'hdfs']}
2017-01-18 12:36:10,605 - FS Type: 
2017-01-18 12:36:10,606 - Directory['/etc/hadoop'] {'mode': 0755}
2017-01-18 12:36:10,633 - File['/usr/hdp/current/hadoop-client/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2017-01-18 12:36:10,634 - Directory['/var/lib/ambari-agent/tmp/hadoop_java_io_tmpdir'] {'owner': 'hdfs', 'group': 'hadoop', 'mode': 01777}
2017-01-18 12:36:10,655 - Execute[('setenforce', '0')] {'not_if': '(! which getenforce ) || (which getenforce && getenforce | grep -q Disabled)', 'sudo': True, 'only_if': 'test -f /selinux/enforce'}
2017-01-18 12:36:10,689 - Skipping Execute[('setenforce', '0')] due to not_if
2017-01-18 12:36:10,689 - Directory['/var/log/hadoop'] {'owner': 'root', 'create_parents': True, 'group': 'hadoop', 'mode': 0775, 'cd_access': 'a'}
2017-01-18 12:36:10,694 - Directory['/var/run/hadoop'] {'owner': 'root', 'create_parents': True, 'group': 'root', 'cd_access': 'a'}
2017-01-18 12:36:10,695 - Directory['/tmp/hadoop-hdfs'] {'owner': 'hdfs', 'create_parents': True, 'cd_access': 'a'}
2017-01-18 12:36:10,704 - File['/usr/hdp/current/hadoop-client/conf/commons-logging.properties'] {'content': Template('commons-logging.properties.j2'), 'owner': 'hdfs'}
2017-01-18 12:36:10,708 - File['/usr/hdp/current/hadoop-client/conf/health_check'] {'content': Template('health_check.j2'), 'owner': 'hdfs'}
2017-01-18 12:36:10,710 - File['/usr/hdp/current/hadoop-client/conf/log4j.properties'] {'content': ..., 'owner': 'hdfs', 'group': 'hadoop', 'mode': 0644}
2017-01-18 12:36:10,734 - File['/usr/hdp/current/hadoop-client/conf/hadoop-metrics2.properties'] {'content': Template('hadoop-metrics2.properties.j2'), 'owner': 'hdfs', 'group': 'hadoop'}
2017-01-18 12:36:10,735 - File['/usr/hdp/current/hadoop-client/conf/task-log4j.properties'] {'content': StaticFile('task-log4j.properties'), 'mode': 0755}
2017-01-18 12:36:10,736 - File['/usr/hdp/current/hadoop-client/conf/configuration.xsl'] {'owner': 'hdfs', 'group': 'hadoop'}
2017-01-18 12:36:10,744 - File['/etc/hadoop/conf/topology_mappings.data'] {'owner': 'hdfs', 'content': Template('topology_mappings.data.j2'), 'only_if': 'test -d /etc/hadoop/conf', 'group': 'hadoop'}
2017-01-18 12:36:10,773 - File['/etc/hadoop/conf/topology_script.py'] {'content': StaticFile('topology_script.py'), 'only_if': 'test -d /etc/hadoop/conf', 'mode': 0755}
2017-01-18 12:36:11,112 - Execute['mkdir -p /etc/presto/catalog'] {}
INFO:resource_management.libraries.script.script:Execute['mkdir -p /etc/presto/catalog'] {}
2017-01-18 12:36:11,143 - Execute['mkdir -p /etc/presto/catalog'] {}
INFO:resource_management.libraries.script.script:Execute['mkdir -p /etc/presto/catalog'] {}
2017-01-18 12:36:11,170 - Execute['/etc/init.d/presto start'] {}
INFO:resource_management.libraries.script.script:Execute['/etc/init.d/presto start'] {}

Command failed after 1 tries

**Comment by teamsoo** [comment]
One error says "sudo: sorry, you must have a tty to run sudo"

That's probably because your /etc/sudoers file (or any file it includes) has:

> Defaults requiretty

...which makes sudo require a TTY. Red Hat systems (RHEL, Fedora...) have been known to require a TTY in default sudoers file. That provides no real security benefit and can be safely removed.

Please check [Requirements for integration](https://github.com/prestodb/ambari-presto-service/blob/master/docs/getting-started.rst)

**Comment by petroav** [comment]
@teamsoo you're exactly correct, I think that's the problem :)

@getway can you try making the suggested change and see if that fixes the issue? I'm closing the issue for now but feel free to re-open if the suggestion doesn't fix your problem.
