### ISSUE TITLE
Presto installation with ambari in HDP 2.6.3

### ISSUE THREAD

**Issue by Sharda-Borse** [prestodb/ambari-presto-service#31]
Hi,
i am trying to install prestodb in hdp2.6.3. 
i am getting **error for presto worker install**
error:
**resource_management.core.exceptions.ExecutionFailed: Execution of 'export JAVA8_HOME=/usr/jdk64/jdk1.8.0_112 && rpm -i /tmp/presto-server-rpm-0.161.rpm' returned 1. package presto-server-rpm-0:0.161-1.x86_64 is already installed**

steps followed for installing presto service:-

Steps:-
download ambari-presto-1.2.tar.gz
create directory PRESTO
# mkdir /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO

# cd /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/

untar ambari-presto in recently created directory
# tar -xvf ambari-presto-1.2.tar.gz -C /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/

move ambari-presto files in PRESTO/
# mv /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/ambari-presto-1.2/* /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO

remove ambari-presto
# rm -rf /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/ambari-presto-1.2
# chmod -R +x /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/*

change below files in configs
- jvm.config add :- "-DHADOOP_USER_NAME=hive"

- /etc/ambari-server/conf/ambari.properties :-
"agent.package.install.task.timeout=5000"

- even after this you may get a error regarding jdk version incompatibility
steps followed to resolve this

# ambari-server setup

# select option to configure jdk and install jdk 1.8 update

https://docs.hortonworks.com/HDPDocuments/Ambari-2.6.0.0/bk_ambari-administration/content/ch_changing_the_jdk_version_on_an_existing_cluster.html

restart ambari server to apply changes
# ambari-server restart

login to ambari UI
Click on add service
select Presto click next
followed configurations as per https://prestodb.io/ambari-presto-service/getting-started.html

Thanks,
Sharda

**Comment by wangv0615** [comment]
you rpm is already installed
you can rpm -qa|grep "presto" to find which rpm you installed
then rpm -e YOU_RPM

**Comment by wangv0615** [comment]
> Hi,
> i am trying to install prestodb in hdp2.6.3.
> i am getting **error for presto worker install**
> error:
> **resource_management.core.exceptions.ExecutionFailed: Execution of 'export JAVA8_HOME=/usr/jdk64/jdk1.8.0_112 && rpm -i /tmp/presto-server-rpm-0.161.rpm' returned 1. package presto-server-rpm-0:0.161-1.x86_64 is already installed**
> 
> steps followed for installing presto service:-
> Steps:-
> download ambari-presto-1.2.tar.gz
> create directory PRESTO
> 
> # mkdir /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO
> # cd /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/
> untar ambari-presto in recently created directory
> 
> # tar -xvf ambari-presto-1.2.tar.gz -C /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/
> move ambari-presto files in PRESTO/
> 
> # mv /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/ambari-presto-1.2/* /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO
> remove ambari-presto
> 
> # rm -rf /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/ambari-presto-1.2
> # chmod -R +x /var/lib/ambari-server/resources/stacks/HDP/2.6/services/PRESTO/*
> change below files in configs
> 
> * /etc/ambari-server/conf/ambari.properties :-
>   "agent.package.install.task.timeout=5000"
> * even after this you may get a error regarding jdk version incompatibility
>   https://docs.hortonworks.com/HDPDocuments/Ambari-2.6.0.0/bk_ambari-administration/content/ch_changing_the_jdk_version_on_an_existing_cluster.html
>   steps followed to resolve this
> 
> # ambari-server setup
> # select option to configure jdk and install jdk 1.8 update
> # ambari-server restart
> login to ambari UI
> Click on add service
> select Presto click next
> followed configurations as per https://prestodb.io/ambari-presto-service/getting-started.html
> added :- - jvm.config add :- "-DHADOOP_USER_NAME=hive"
> 
> **Error log for Presto worker install:-**
> 
> Traceback (most recent call last):
> File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/PRESTO/package/scripts/presto_worker.py", line 74, in
> Worker().execute()
> File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 367, in execute
> method(env)
> File "/var/lib/ambari-agent/cache/stacks/HDP/2.6/services/PRESTO/package/scripts/presto_worker.py", line 28, in install
> Execute('export JAVA8_HOME={0} && rpm -i /tmp/{1}'.format(java_home, PRESTO_RPM_NAME))
> File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 166, in **init**
> self.env.run()
> File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 160, in run
> self.run_action(resource, action)
> File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 124, in run_action
> provider_action()
> File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 262, in action_run
> tries=self.resource.tries, try_sleep=self.resource.try_sleep)
> File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 72, in inner
> result = function(command, **kwargs)
> File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 102, in checked_call
> tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy)
> File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 150, in _call_wrapper
> result = _call(command, **kwargs_copy)
> File "/usr/lib/python2.6/site-packages/resource_management/core/shell.py", line 303, in _call
> raise ExecutionFailed(err_msg, code, out, err)
> resource_management.core.exceptions.ExecutionFailed: Execution of 'export JAVA8_HOME=/usr/jdk64/jdk1.8.0_112 && rpm -i /tmp/presto-server-rpm-0.161.rpm' returned 1. package presto-server-rpm-0:0.161-1.x86_64 is already installed
> 
> Thanks,
> Sharda

you rpm is already installed
you can rpm -qa|grep "presto" to find which rpm you installed
then rpm -e YOU_RPM
